[package]
name = "targo"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
blake3 = "1.3.1"
camino = { version = "1.1.1", features = ["serde1"] }
chrono = { version = "0.4.22", features = ["serde"] }
fs2 = "0.4.3"
toml = "0.5.8"
lexopt = { version = "0.2.1" }
color-eyre = { version = "0.6.2", default-features = false }
shell-words = { version = "1.1.0" }
semver = { version = "1.0.14", features = ["serde"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
home = "0.5.4"
bs58 = "0.4.0"
clap = { version = "4.0.17", features = ["derive"] }
